### ISSUE TITLE
Refactor user story.

### ISSUE THREAD

**Issue by PranavaaKirupakaran** [PranavaaKirupakaran/SOEN341_Project#16]
As a user, I want to able to create/login into my account so that I can have my own personalized account from where i can track my purchases and items that I would like to purchase in the future.

- [ ] Create a login page where the user can input his password and username.
- [ ] Create a database table containing the username and password.
- [ ] Implement back-end for the login page.
- [ ] Link the database to the login page.
- [ ] Create a list that contains the user's purchase history in the user's account.
- [ ] Create a database table containing each account's purchase history.
- [ ] Implement back-end for the list.
- [ ] Link the database containing the account's purchase history to the user's account.

**Comment by spaceGB** [comment]
Closing this issues, refactored user story.
