### ISSUE TITLE
Perform risk analysis and risk management.

### ISSUE THREAD

**Issue by PranavaaKirupakaran** [PranavaaKirupakaran/SOEN341_Project#27]

**Comment by spaceGB** [comment]
Risk assessment was completed. Risk analysis was carried out by looking into each story and determining potential risks, consequences, as well as countermeasures. Additionally, a risk matrix was applied to determine the appropiate risk level. The matrix included the probability and impact of each risk going from Low, to Medium, and finally, High. The matrix was a very useful tool to determine the overall risk levels. What is more, other risks related to the overall project were also discussed.
