### ISSUE TITLE
Perform preliminary risk analysis.

### ISSUE THREAD

**Issue by miraaji** [PranavaaKirupakaran/SOEN341_Project#29]
Risk: Security flaw arises. 
Probability: Low. 
Effect: Catastrophic. 
Solution: assign more people with good knowledge about cyber security to ensure that the website is as secure as possible.

Risk: Group member leaves the project. 
Probability: Moderate. 
Effect: Serious. 
Solution: make sure that every group member knows what other members' jobs include. 

Risk: Time risk/ underestimating time required to get sprint requirements done. 
Probability: Low. 
Effect: Moderate. 
Solution: assign more time than you think is required to get sprint requirements done.

Risk: insufficient resources to complete the app. 
Probability: Low. 
Effect: Serious. 
Solution: make sure that all resources required to finish the product are available on time.

**Comment by spaceGB** [comment]
Move issues to another document.
