### ISSUE TITLE
User Story #1: As a User, I want to be able to have my own profile because it will allow me to store personal information for future use.

### ISSUE THREAD

**Issue by spaceGB** [PranavaaKirupakaran/SOEN341_Project#30]
Associated Tasks :
- #31 
- #32

**Comment by Amine-Bouras** [comment]
**Acceptance test**
 - Click on the register button
 - Redirect to the register form
 - Enter my valid personal information to create an account (name, email, password)
 - When clicking the register button create my account with all my information
 - When clicking the register button redirect me to the main page
 - Hover over the my account button and access the drop down menu
 - When clicking on dashboard or my profile redirect me to its respective page
 - When clicking on logout I want to be redirected from the main page but not in my account

**Comment by PranavaaKirupakaran** [comment]
Unsuccessful test
 - Click on the register button
 - Redirect to the register form
 - Enter my non-valid personal information (invalid or blank email address field)
 - When clicking the register button account will not be created and user will be prompted to add a valid email address
 - Enter my valid personal information to create an account (name, email, password)
 - When clicking the register button redirect me to the main page
 - When clicking the register button redirect me to the main page
 - Hover over the my account button and access the drop down menu
 - When clicking on dashboard or my profile redirect me to its respective page
 - When clicking on logout I want to be redirected from the main page but not in my account
 
 Unsuccessful test
 - Click on the register button
 - Redirect to the register form
 - Enter my non-valid personal information (enter password with less than 8 characters)
 - When clicking the register button account will not be created and user will be prompted to add a valid password
 - Enter my valid personal information to create an account (name, email, password)
 - When clicking the register button redirect me to the main page
 - When clicking the register button redirect me to the main page
 - Hover over the my account button and access the drop down menu
 - When clicking on dashboard or my profile redirect me to its respective page
 - When clicking on logout I want to be redirected from the main page but not in my account

**Comment by spaceGB** [comment]
Initial tasks for the story have been implemented, waiting for review.

**Comment by PranavaaKirupakaran** [comment]
User story #1 (issue #30)
Acceptance Test:
Succesful Test
 - Click on the register button
 - Redirect to the register form
 - Enter my valid personal information to create an account (name, email, password)
 - When clicking the register button create my account with all my information
 - When clicking the register button redirect me to the main page
 - Hover over the my account button and access the dropdown menu
 - When clicking on dashboard or my profile redirect me to its respective page
 - When clicking on logout I want to be redirected from the main page but not in my account
 
Unsuccesful test
 - Click on the register button
 - Redirect to the register form
 - Enter my non-valid personal information (invalid or blank email address field)
 - When clicking the register button account will not be created and user will be prompted to add a valid email address
 - Enter my valid personal information to create an account (name, email, password)
 - When clicking the register button redirect me to the main page
 - When clicking the register button redirect me to the main page
 - Hover over the my account button and access the dropdown menu
 - When clicking on dashboard or my profile redirect me to its respective page
 - When clicking on logout I want to be redirected from the main page but not in my account

 Unsuccesful test
 - Click on the register button
 - Redirect to the register form
 - Enter my non-valid personal information (enter password with less than 8 characters)
 - When clicking the register button account will not be created and user will be prompted to add a valid password
 - Enter my valid personal information to create an account (name, email, password)
 - When clicking the register button redirect me to the main page
 - When clicking the register button redirect me to the main page
 - Hover over the my account button and access the dropdown menu
 - When clicking on dashboard or my profile redirect me to its respective page
 - When clicking on logout I want to be redirected from the main page but not in my account
