### ISSUE TITLE
User Story #2: As a User, I want to be able to access my account because it will allow me to manage my personal profile.

### ISSUE THREAD

**Issue by spaceGB** [PranavaaKirupakaran/SOEN341_Project#33]

**Comment by PranavaaKirupakaran** [comment]
Related Task:
- #34 
- #35 
- #36

**Comment by spaceGB** [comment]
Tasks concerning this story were originally implemented for sprint 2. The story will remain open as possible new improvements will be discussed after receiving user feedback.
