### ISSUE TITLE
User Story #3: As a User, I want to browse through the product catalogue because it will allow me to see all the options available for me.

### ISSUE THREAD

**Issue by spaceGB** [PranavaaKirupakaran/SOEN341_Project#37]
Related Tasks:
- #38 
- #39

**Comment by SFarhatComp** [comment]
Acceptance Test:
Succesful Test
  - Click on shop button on the main page
  - This will bring the shop page with the products
  - Browse through the different products
  - When scrolling donw the page, more items should be loaded
  - When pressing on the next,prev button, the equivalent page should be loaded

**Comment by spaceGB** [comment]
Basic browsing functionality works as expected.
