### ISSUE TITLE
User Story #4: As a User, I want to search through the product catalogue because I can find specific items without specifying additional criteria.

### ISSUE THREAD

**Issue by spaceGB** [PranavaaKirupakaran/SOEN341_Project#40]
Related Tasks:
- #41 
- #42

**Comment by PranavaaKirupakaran** [comment]
User Story #4 (Issue 40)
Acceptance Test:
Succesful Test:
  - Click on "Shop" button on the main page
  - Redirect user to the shopping page with the products
  - Enter a valid keyword into the search bar
  - Click the search button (magnifying glass icon)
  - Results containing specifed keyword should be displayed

Succesful Test:
  - Click on "Shop" button on the main page
  - Redirect user to the shopping page with the products
  - Enter a invalid keyword into the search bar
  - Click the search button (magnifying glass icon)
  - Message saying no items was found should be displayed
