### ISSUE TITLE
User Story #8: As a User, I want to have a shopping cart because it will allow me to buy as many products as I need.

### ISSUE THREAD

**Issue by spaceGB** [PranavaaKirupakaran/SOEN341_Project#51]
Related Tasks:
- #52 
- #53 
- #54 
- #55

**Comment by PranavaaKirupakaran** [comment]
User Story #8 (Issue #51)
 Acceptance Test:
 Successful Test:
  - Click on add button below the product of interest
  - The button will add the product to my cart and update my receipt
  - When clicking the view cart button, it will redirect me to my shopping cart page
  - On the shopping cart page I will be able to see all the products that I added to the shopping cart
  - When clicking on the Add button next to the product on my shopping cart, it will increase the quantity and update my receipt accordingly
  - When clicking on the Delete button next to the product on my shopping cart, it will decrease the quantity and update my receipt accordingly
  - When clicking on the purchase button, I will be redirected from the shopping cart page and prompted to enter my method of payment
