### ISSUE TITLE
User Story #11: As a Customer, I want to add product reviews because it will allow me to share my experience and opinion with other customers.

### ISSUE THREAD

**Issue by spaceGB** [PranavaaKirupakaran/SOEN341_Project#62]
Related Tasks:
- #63 
- #64

**Comment by PranavaaKirupakaran** [comment]
User Story #11 (Issue #62)
Acceptance Test:
Successful Test:
  -After buying a product and it has been delivered, a prompt will ask if we want to leave a review
  -I leave the review and post the review
  -When I post, the review is now availlable for all to see under the review section of the product.
 
 Unsuccesful Test:

  - I go into my past purchased items
  - I click on leave a review
  - The review form dosn't appear
 
  - I go into my past purchased items
  - I click on leave a review
  - The review form appear and I leave my review, then publish it
  - The review does not get published under the product's review section.
