### ISSUE TITLE
Look into the login functionality.

### ISSUE THREAD

**Issue by PranavaaKirupakaran** [PranavaaKirupakaran/SOEN341_Project#8]
The login feature should be fixed before the end of the next sprint. No exact date has been established yet, most likely one week into S print #2.

**Comment by PranavaaKirupakaran** [comment]
@PranavaaKirupakaran, @SFarhatComp and @Vraj2301 will be taking care of this.

**Comment by Vraj2301** [comment]
We will start working on it after from today
